### ISSUE TITLE
Update Clojure 1.11.1 build

### ISSUE THREAD

**Issue by wtfleming** [CircleCI-Public/cimg-clojure#41]
Would it be possible to update this to use a newer build of Clojure?

`cimg/clojure:1.11.1` and `cimg/clojure:1.11.1-openjdk-17.0` are both using Clojure `1.11.1.1105`
https://github.com/CircleCI-Public/cimg-clojure/blob/main/1.11/Dockerfile#L12

However, I am seeing sporadic build errors in circleci due to a bug in Clojure. The bug appears to have been fixed in Clojure `1.11.1.1113` https://clojure.org/releases/tools#v1.11.1.1113

FWIW the exception I am seeing is

```
Error building classpath. class java.util.HashMap$Node cannot be cast to class java.util.HashMap$TreeNode (java.util.HashMap$Node and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.util.HashMap$Node cannot be cast to class java.util.HashMap$TreeNode (java.util.HashMap$Node and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')
	at java.base/java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1986)
	at java.base/java.util.HashMap$TreeNode.treeify(HashMap.java:2102)
	at java.base/java.util.HashMap.treeifyBin(HashMap.java:770)
	at java.base/java.util.HashMap.putVal(HashMap.java:642)
	at java.base/java.util.HashMap.put(HashMap.java:610)
	at java.base/java.util.HashSet.add(HashSet.java:221)
	at org.apache.maven.model.validation.DefaultModelValidator.validateId(DefaultModelValidator.java:848)
	at org.apache.maven.model.validation.DefaultModelValidator.validateEffectiveDependency(DefaultModelValidator.java:663)
	at org.apache.maven.model.validation.DefaultModelValidator.validateEffectiveDependencies(DefaultModelValidator.java:584)
	at org.apache.maven.model.validation.DefaultModelValidator.validateEffectiveModel(DefaultModelValidator.java:374)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:501)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:437)
	at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement(DefaultModelBuilder.java:1306)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:481)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:437)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:252)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:297)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:175)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:255)
	at clojure.tools.deps.alpha.extensions.maven$read_descriptor.invokeStatic(maven.clj:115)
	at clojure.tools.deps.alpha.extensions.maven$fn__1128.invokeStatic(maven.clj:143)
	at clojure.tools.deps.alpha.extensions.maven$fn__1128.invoke(maven.clj:143)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at clojure.tools.deps.alpha$expand_deps$children_task__771$fn__773$fn__774.invoke(alpha.clj:405)
	at clojure.tools.deps.alpha.util.concurrent$submit_task$task__479.invoke(concurrent.clj:35)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

`1.11.1.1113` has a fix for the issue with maven

thanks!

**Comment by JalexChen** [comment]
hey @wtfleming - thanks for bringing this to our attention. Would you have happened to try using an image with those updated tool versions for clojure? we don't typically cut additional releases for the same version unless it's security related and since i don't have access to your build, i wouldn't be able to repro or confirm the actual issue.

Could you please let us know and we'll update given 1) it fixes your issue and 2) clojure does not change versions often?

**Comment by JalexChen** [comment]
hey @wtfleming - we've republished the image with updated tools. you should be good to go now

**Comment by wtfleming** [comment]
thank you!
